### ISSUE TITLE
[parse-tika] class path issue if parsing recursively

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/nutch#12]
For charset detection (as a precondition of language detection) the tika-parser jar is required as a core dependency without recursive dependencies. However, when parsing documents using parse-tika and parsers are called recursively for documents which contain other documents (eg. office docs with embedded docs - images, etc.) the parsing fails because for the recursive parses the parsers from the main class loader and not the plugin class loader is used:
```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/drew/metadata/MetadataException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.apache.nutch.parse.ParseUtil.runParser(ParseUtil.java:188)
        at org.apache.nutch.parse.ParseUtil.parse(ParseUtil.java:92)
        ...
Caused by: java.lang.NoClassDefFoundError: com/drew/metadata/MetadataException
        at org.apache.tika.parser.jpeg.JpegParser.parse(JpegParser.java:58)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
        at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
        at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104)
        at org.apache.tika.parser.epub.EpubParser.handleEmbedded(EpubParser.java:358)
        at org.apache.tika.parser.epub.EpubParser.bufferedParseZipFile(EpubParser.java:301)
        at org.apache.tika.parser.epub.EpubParser.bufferedParse(EpubParser.java:202)
        at org.apache.tika.parser.epub.EpubParser.parse(EpubParser.java:128)
        at org.apache.nutch.parse.tika.TikaParser.getParse(TikaParser.java:144)
        at org.apache.nutch.parse.tika.TikaParser.getParse(TikaParser.java:86)
        at org.apache.nutch.parse.ParseCallable.call(ParseCallable.java:34)
        at org.apache.nutch.parse.ParseCallable.call(ParseCallable.java:23)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.drew.metadata.MetadataException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 18 more
```

Note: this is not an issue when running the main crawl (because no parsing is done)

Figure out why the plugin class loader is not used (the plugin class path should always take precedence because there might be version conflicts).

**Comment by sebastian-nagel** [comment]
Fixed in c9238a1 / [NUTCH-2457](https://issues.apache.org/jira/browse/NUTCH-2457) / apache/nutch#474, verified in the latest seed crawl in preparation of the November crawl (CC-MAIN-2019-47).
